name = "Chillpreneur"
license = "MIT"
licenselink = "https://github.com/splatrac/chillpreneur?tab=MIT-1-ov-file#readme"
description = "Chillpreneur is a laid-back, pastel-themed Hugo template designed for creative small businesses and entrepreneurs who value both style and simplicity. With its soft color palette and clean design, Chillpreneur offers an inviting and friendly user experience, perfect for showcasing products, services, or portfolios. Ideal for startups, freelancers, and lifestyle brands, this theme keeps things professional without sacrificing a relaxed, approachable vibe—just the right blend of business and chill!"
homepage = "https://github.com/splatrac/chillpreneur/"

tags = [
    "blog",
    "responsive",
    "personal",
    "light",
    "bootstrap",
    "portfolio",
    "landing",
    "company",
    "modern",
]
features = []

[author]
name = "Splatrac"
homepage = "https://splatrac.me/"
