name = "Chillpreneur"
license = "MIT"
licenselink = "https://github.com/splatrac/chillpreneur?tab=MIT-1-ov-file#readme"
description = "A clean and modern landing page website inspired by clean and modern illustrations."
homepage = "https://github.com/splatrac/chillpreneur/"

tags = [
    "blog",
    "responsive",
    "personal",
    "light",
    "bootstrap",
    "portfolio",
    "landing",
    "company",
    "modern",
]
features = []

[author]
name = "Splatrac"
homepage = "https://splatrac.me/"
